on: 
  push:
    branches:
      - main 
      - "release/**"
    pahts:
      - "src/**"

  pull_request:
    branches:
      - main
      - "release/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: run tests
      run: npm test
